config/routes.rb
Rails.application.routes.draw do
  get 'signup/index'
  post 'signup/login' => 'signup#login', :as => :signup_login
  delete 'signup/logout' => 'signup#logout', :as => :signup_logout
  get 'signup/profile'
  root 'signup#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  include SignupHelper
  include ApplicationHelper

  def index
    if logged_in?
      redirect_to action: 'profile'
    end
  end

  def login
    user_params = log_in params[:token]
    if user_params.nil?
      flash[:error] = 'Não foi possível realizar o login, tente novamente.'
      render :json => {
          :status => 'error',
          :location => url_for(:controller => 'signup', :action => 'index')
      }
      return
    end

    @user = User.find_by_id( user_params['user_id'])
    if @user.nil?
      @user = User.create(id: user_params['user_id'])
    end
    @user.email = user_params['email']
    @user.name = user_params['name']
    @user.picture_url = user_params['picture_url']

    logger.debug user_params

    if request.xhr?
      if @user.save
        render :json => {
            :status => :created,
            :location => url_for(:controller => 'signup', :action => 'profile')
        }
      end

    end
  end

  def logout
    user_logout
    redirect_to action: 'index'
  end

  def profile
    unless logged_in?
      redirect_to action: 'index'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when 'success'
        'alert-success' # Green
      when 'error'
        'alert-danger' # Red
      when 'alert'
        'alert-warning' # Yellow
      when 'notice'
        'alert-info' # Blue
      else
        flash_type.to_s
    end
  end
  def current_user
    @current_user ||= User.find_by_id(session[:id])
  end
  def logged_in?
    !current_user.nil?
  end
  def user_logout
    session[:id] = nil
  end


end

app/helpers/signup_helper.rb
module SignupHelper

  def log_in(token)
    @api = CoffeeApiService.new
    user_info = JSON.parse(@api.user_info(token).body)
    unless user_info.nil? or user_info.empty?
      session[:token] = token
      session[:id] = user_info['user_id']
    end
    user_info
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'shared/navbar' %>
  <div class="container">
    <%= render partial: 'shared/flash_messages', flash: flash %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade in">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= message %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to('', '#') %></li>
        <li><%= link_to('', '#') %></li>
        <li><%= link_to('', '#') %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= link_to('My Account', signup_index_path) %></li>
            <li><%= link_to "Sign out", signup_logout_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to('Sign in', signup_index_path) %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/signup/index.html.erb
<div class="row">
  <div id='login-c6ab6f67'  class="col-md-offset-2" style='display: table; margin: 0 auto;'></div>
</div>
<script>
    (function () {
        if (typeof(window.socialid) !== "object") window.socialid = {};


        socialid.onLoad = function () {
            socialid.login.init(422, {loginType: "event"});
            socialid.login.renderLoginWidget("login-c6ab6f67",
                {
                    "providers": ["facebook", "gplus", "twitter", "linkedin"],
                    "theme": "bricks",
                    "showSocialIdLink": true
                });
            eventHandlers();
        };

        var e = document.createElement('script');
        e.type = 'text/javascript';
        e.id = 'socialid_api_script';
        if (document.location.protocol === 'https:') {
            e.src = 'https://staging.socialidnow.com/assets/api/socialid.js';
        } else {
            e.src = 'http://staging.socialidnow.com/assets/api/socialid.js';
        }
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(e, s);
    })();
</script>

app/views/signup/profile.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3">
    <div class="well well-sm">
      <div class="row">
        <div class="col-sm-6 col-md-4">
          <img src="<%= current_user.picture_url %>" alt="" class="img-rounded img-responsive css-big-img"/>
        </div>
        <div class="col-sm-6 col-md-8">
          <h4>
            <%= current_user.name %></h4>
          <p>
            <i class="glyphicon glyphicon-envelope"></i>    <%= current_user.email %>
            <br/>
            <br/>
            <i class="glyphicon glyphicon-barcode"></i>  <%= truncate(session[:token], length:30) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>